create table if not exists public.marking_sessions (
  id bigint generated by default as identity primary key,
  exam_board text not null,
  mode text not null,
  question_text text not null default '',
  answer_text text not null default '',
  upload_name text not null default '',
  score integer not null default 0,
  feedback jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  email text not null,
  plan text not null,
  status text not null default 'active',
  provider text not null default 'stripe_link',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists marking_sessions_created_at_idx on public.marking_sessions (created_at desc);
create index if not exists subscriptions_created_at_idx on public.subscriptions (created_at desc);
create index if not exists subscriptions_email_idx on public.subscriptions (email);

alter table public.marking_sessions
  alter column created_at set default now();

alter table public.subscriptions
  alter column created_at set default now();

grant usage on schema public to anon, authenticated;
grant select, insert on public.marking_sessions to anon, authenticated;
grant select, insert on public.subscriptions to anon, authenticated;
